# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.runs/synth_1/mb_usb_hdmi_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.cache/wt [current_project]
set_property parent.project_path C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/hdmi_tx_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/duck_hunt_v2/duck_hunt_v2.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/duck_hunt_v2/duck_hunt_v2.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/duckhunt_rightfacing_wingup/duckhunt_rightfacing_wingup.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/goose_wingup/goose_wingup.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose1/Goose1.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose_wing_up/Goose_wing_up.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose_wing_mid/Goose_wing_mid.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose_wing_down/Goose_wing_down.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose_fall/Goose_fall.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_excited/dog_excited.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_sniff/dog_sniff.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_walk_first/dog_walk_first.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_walk_second/dog_walk_second.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_walk_third/dog_walk_third.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_walk_fourth/dog_walk_fourth.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_jump1/dog_jump1.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_jump2/dog_jump2.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_standing/dog_standing.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/dog_laugh1/dog_laugh1.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose_fly_away1/Goose_fly_away1.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose_fly_away2/Goose_fly_away2.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/Goose_fly_away3/Goose_fly_away3.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/duck_hunt_v3/duck_hunt_v3.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/game_over/game_over.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_0/num_0.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_1/num_1.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_2/num_2.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_3/num_3.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_4/num_4.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_5/num_5.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_6/num_6.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_7/num_7.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_8/num_8.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_9/num_9.COE
add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_10/num_10.COE
add_files c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_0/num_0_v2.COE
add_files c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_1/num_1_v2.COE
add_files c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/num_2/num_2_v2.COE
add_files c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/Image_to_COE/duck_hunt_end/duck_hunt_end.COE
read_verilog -library xil_defaultlib -sv {
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/design_source/Color_Mapper.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Goose_fall/Goose_fall_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/Goose_fly_away1/Goose_fly_away1_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/Goose_fly_away2/Goose_fly_away2_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/Goose_fly_away3/Goose_fly_away3_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/Goose_wing_down/Goose_wing_down_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/Goose_wing_mid/Goose_wing_mid_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/Goose_wing_up/Goose_wing_up_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/design_source/VGA_controller.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/design_source/ball.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/new/binary_to_decimal.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/new/control.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/new/dog.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_excited/dog_excited_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_jump1/dog_jump1_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_jump2/dog_jump2_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_laugh1/dog_laugh1_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_sniff/dog_sniff_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_standing/dog_standing_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_walk_first/dog_walk_first_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_walk_fourth/dog_walk_fourth_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_walk_second/dog_walk_second_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/dog_walk_third/dog_walk_third_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/new/duck.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/duck_hunt_end/duck_hunt_end_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/duck_hunt_v2/duck_hunt_v2_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/design_source/hex_driver.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/new/lfsr.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/385_Vivado_Projects/negedge_detector.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_0/num_0_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_10/num_10_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_1/num_1_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_2/num_2_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_3/num_3_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_4/num_4_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_5/num_5_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_6/num_6_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_7/num_7_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_8/num_8_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/Image_to_COE/num_9/num_9_palette.sv
  C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/imports/design_source/mb_usb_hdmi_top.sv
}
read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/Goose_fly_away1_rom/Goose_fly_away1_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/Goose_fly_away1_rom/Goose_fly_away1_rom_ooc.xdc]

add_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/bd/mb_block/mb_block.bd
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_dlmb_v10_0/mb_block_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_dlmb_bram_if_cntlr_0/mb_block_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_bram_if_cntlr_0/mb_block_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_lmb_bram_0/mb_block_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_mdm_1_0/mb_block_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_mdm_1_0/mb_block_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0/mb_block_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0/mb_block_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_1_0/mb_block_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_0/mb_block_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_1/mb_block_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_1/mb_block_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_1/mb_block_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/mb_block_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_2/mb_block_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_2/mb_block_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_0_2/mb_block_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/mb_block_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_0/data/mb_bootloop_le.elf]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/duck_hunt_v2_rom/duck_hunt_v2_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/duck_hunt_v2_rom/duck_hunt_v2_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/Goose_wing_up_rom/Goose_wing_up_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/Goose_wing_up_rom/Goose_wing_up_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/Goose_wing_mid_rom/Goose_wing_mid_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/Goose_wing_mid_rom/Goose_wing_mid_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/Goose_wing_down_rom/Goose_wing_down_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/Goose_wing_down_rom/Goose_wing_down_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/Goose_fall_rom/Goose_fall_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/Goose_fall_rom/Goose_fall_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_excited_rom/dog_excited_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_excited_rom/dog_excited_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_sniff_rom/dog_sniff_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_sniff_rom/dog_sniff_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_walk_first_rom/dog_walk_first_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_walk_first_rom/dog_walk_first_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_walk_second_rom/dog_walk_second_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_walk_second_rom/dog_walk_second_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_walk_third_rom/dog_walk_third_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_walk_third_rom/dog_walk_third_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/duck_walk_fourth_rom/duck_walk_fourth_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/duck_walk_fourth_rom/duck_walk_fourth_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_jump1_rom/dog_jump1_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_jump1_rom/dog_jump1_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_jump2_rom/dog_jump2_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_jump2_rom/dog_jump2_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_standing_rom/dog_standing_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_standing_rom/dog_standing_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_laugh1_rom/dog_laugh1_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_laugh1_rom/dog_laugh1_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/Goose_fly_away2_rom/Goose_fly_away2_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/Goose_fly_away2_rom/Goose_fly_away2_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/Goose_fly_away3/Goose_fly_away3.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/Goose_fly_away3/Goose_fly_away3_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_0_rom/num_0_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_0_rom/num_0_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_1_rom/num_1_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_1_rom/num_1_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_2_rom/num_2_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_2_rom/num_2_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_3_rom/num_3_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_3_rom/num_3_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_4_rom/num_4_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_4_rom/num_4_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_5_rom/num_5_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_5_rom/num_5_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_6_rom/num_6_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_6_rom/num_6_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_7_rom/num_7_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_7_rom/num_7_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_8_rom/num_8_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_8_rom/num_8_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_9_rom/num_9_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_9_rom/num_9_rom_ooc.xdc]

read_ip -quiet C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/num_10_rom/num_10_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/num_10_rom/num_10_rom_ooc.xdc]

read_ip -quiet c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/duck_hunt_end_rom/duck_hunt_end_rom.xci
set_property used_in_implementation false [get_files -all c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/duck_hunt_end_rom/duck_hunt_end_rom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc
set_property used_in_implementation false [get_files C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/utils_1/imports/synth_1/mb_usb_hdmi_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mb_usb_hdmi_top -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mb_usb_hdmi_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mb_usb_hdmi_top_utilization_synth.rpt -pb mb_usb_hdmi_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
