# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_laugh1_rom/dog_laugh1_rom.xci
# IP: The module: 'dog_laugh1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_laugh1_rom/dog_laugh1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dog_laugh1_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.srcs/sources_1/ip/dog_laugh1_rom/dog_laugh1_rom.xci
# IP: The module: 'dog_laugh1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/385_Vivado_Projects/Final_Project/ECE-385-Final-Project/goose_hunt/goose_hunt.gen/sources_1/ip/dog_laugh1_rom/dog_laugh1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dog_laugh1_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
